### ISSUE TITLE
What is jsut.p file looks like? Can you provide one?

### ISSUE THREAD

**Issue by Hendry2182** [kodamanbou/Voice-Conversion-with-TF2.0#29]
Dear Kodamanbou, it is a very nice implementation of VC GAN here. May I know what is jsut.p file looks like. I have problem in implementing the just.p file.

Best Regards

Hendry

-- Done, sorry for the inconvenience, that file is generated from the preproces.py. Thank you

**Comment by kodamanbou** [comment]
Sorry for the late reply.
Yes, you can generate jsut.p by using preprocess.py.
Good luck !!!!
